services:
  db:
    image: postgres:17-alpine
    container_name: nexbarber-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lamotte
      POSTGRES_DB: gestion_appr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: